#!/bin/bash
# RALPH ORCHESTRATOR QUICK START

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   Ralph Multi-Agent Orchestration - Quick Start                ║"
echo "║   Run autonomous Angular development with 3-10 parallel agents ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Check if in correct directory
if [ ! -f "ralph-orchestrator.sh" ]; then
    echo "❌ Error: Run this from the project root"
    echo "   cd /home/spanexx/Shared/Learn/go_tutorials/social-media"
    exit 1
fi

echo "🧪 STEP 1: Run Validation Test (No qwen execution)"
echo "─────────────────────────────────────────────────"
echo ""
echo "  Command: ./ralph-orchestrator-dryrun.sh"
echo "  Purpose: Validates coordination layer, state mgmt, atomic operations"
echo "  Time:    ~15 seconds"
echo ""
echo "  Run it with: bash ./ralph-orchestrator-dryrun.sh"
echo ""

echo "🚀 STEP 2: Launch Multi-Agent Development"
echo "──────────────────────────────────────────"
echo ""
echo "  With 3 workers (default):"
echo "    ./ralph-orchestrator.sh 3"
echo ""
echo "  With 5 workers (more parallelism):"
echo "    ./ralph-orchestrator.sh 5"
echo ""
echo "  With 10 workers (aggressive):"
echo "    ./ralph-orchestrator.sh 10"
echo ""

echo "  You can also run against an explicit tasks file:"
echo "    ./ralph-orchestrator.sh 3 ralph-tasks.json"
echo ""
echo "  Or explicitly point at the plan folder (tasks will be generated):"
echo "    ./ralph-orchestrator.sh 3 docs/PLAN"
echo ""

echo "📊 STEP 3: Monitor Progress"
echo "───────────────────────────"
echo ""
echo "  In a separate terminal:"
echo ""
echo "    # Watch worker logs in real-time"
echo "    tail -f .ralph/worker-*.log"
echo ""
echo "    # Check queue status"
echo "    jq '.' .ralph/work-queue.json | grep -E 'status|id'"
echo ""
echo "    # View aggregated results"
echo "    jq '.' .ralph/results.json"
echo ""

echo "📄 STEP 4: Review Results"
echo "─────────────────────────"
echo ""
echo "  After orchestration completes:"
echo ""
echo "    cat .ralph/ORCHESTRATOR-REPORT.md"
echo ""
echo "  Find:"
echo "    ✓ Per-worker execution summaries"
echo "    ✓ Findings from each agent iteration"
echo "    ✓ Session timestamps and heartbeats"
echo "    ✓ Task completion status"
echo ""

echo "⚙️  WHAT HAPPENS DURING EXECUTION"
echo "─────────────────────────────────"
echo ""
echo "  1. Orchestrator creates .ralph/ state directory"
echo "  2. Work queue initialized with 5 development tasks:"
echo "     - analyze-feed (high priority)"
echo "     - refactor-post-card (high priority)"
echo "     - improve-messaging (medium priority)"
echo "     - enhance-profile (medium priority)"
echo "     - add-notifications (low priority)"
echo ""
echo "  3. N workers spawned as background processes"
echo "  4. Each worker:"
echo "     - Registers with orchestration layer"
echo "     - Claims task atomically (prevents conflicts)"
echo "     - Runs qwen agent on assigned task"
echo "     - Reports findings back"
echo "     - Continues until queue empty"
echo ""
echo "  5. Orchestrator monitors for 5 minutes"
echo "  6. Results aggregated into .ralph/ORCHESTRATOR-REPORT.md"
echo "  7. All workers shut down gracefully"
echo ""

echo "📁 OUTPUT FILES"
echo "───────────────"
echo ""
echo "  .ralph/"
echo "  ├── state.json                 # Master coordination state"
echo "  ├── work-queue.json            # Task queue (pending→claimed→completed)"
echo "  ├── results.json               # Aggregated findings"
echo "  ├── sessions/"
echo "  │   ├── worker-1.session       # Worker 1 status & findings"
echo "  │   ├── worker-2.session       # Worker 2 status & findings"
echo "  │   └── worker-3.session       # etc..."
echo "  ├── worker-1.log               # Worker 1 execution log"
echo "  ├── worker-2.log               # Worker 2 execution log"
echo "  ├── worker-3.log               # etc..."
echo "  └── .lock                      # File lock for atomic operations"
echo ""
echo "  ORCHESTRATOR-REPORT.md         # Final aggregated report"
echo ""

echo "🎯 RECOMMENDED FIRST RUN"
echo "────────────────────────"
echo ""
echo "  # Step 1: Validate system works"
echo "  bash ./ralph-orchestrator-dryrun.sh"
echo ""
echo "  # Step 2: Launch 3-worker development"
echo "  ./ralph-orchestrator.sh 3"
echo ""
echo "  # Step 3: Monitor in another terminal"
echo "  tail -f .ralph/worker-*.log"
echo ""
echo "  # Step 4: View results"
echo "  cat .ralph/ORCHESTRATOR-REPORT.md"
echo ""

echo "💡 FEATURES"
echo "──────────"
echo ""
echo "  ✅ Parallel Development      - 3-10+ agents working simultaneously"
echo "  ✅ Atomic Operations         - File locking prevents conflicts"
echo "  ✅ State Isolation           - Each worker independent session"
echo "  ✅ Result Aggregation        - Centralized findings collection"
echo "  ✅ Fault Tolerance           - Worker crashes don't corrupt state"
echo "  ✅ Live Monitoring           - Real-time progress tracking"
echo "  ✅ Graceful Shutdown         - Signal handling for clean exit"
echo ""

echo "📚 DOCUMENTATION"
echo "────────────────"
echo ""
echo "  RALPH-ORCHESTRATOR-GUIDE.md     - Complete system documentation"
echo "  RALPH-ORCHESTRATOR-SUMMARY.md   - Implementation summary"
echo "  RALPH-QUICKSTART.md             - Original Ralph guide"
echo "  RALPH-GUIDE.md                  - Advanced Ralph documentation"
echo ""

echo "❓ NEED HELP?"
echo "─────────────"
echo ""
echo "  Issue: Workers not claiming tasks"
echo "  Fix:   rm .ralph/.lock && try again"
echo ""
echo "  Issue: Worker exits early"
echo "  Fix:   tail -f .ralph/worker-N.log (check logs)"
echo ""
echo "  Issue: Results not aggregating"
echo "  Fix:   check .ralph/ permissions, disk space"
echo ""

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                   Ready to Start? 🚀                           ║"
echo "║   Run: ./ralph-orchestrator.sh 3                               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
